name: Package

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set image tags
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        echo "IMAGE_NAME=ghcr.io/serraict/production_control" >> $GITHUB_ENV
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and tag Docker images
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ env.VERSION }} -t ${{ env.IMAGE_NAME }}:latest .
    
    - name: Publish Docker images
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker push ${{ env.IMAGE_NAME }}:latest
